[project]
name = "Quantum Virtual Machine"
version = "0.0.1"
description = "Framework for Virtual and Distributed Quantum Computing"
authors = [
    {name = "Nathaniel Tornow", email = "nathaniel.tornow@tum.de"},
]
dependencies = [
    "qiskit>=0.41.1",
    "networkx>=3.0",
    "qiskit-ibmq-provider>=0.20.1",
    "setuptools>=67.6.0",
    "clingo>=5.6.2",
    "mapomatic>=0.8.0",
    "numpy>=1.23.5",
    "tensornetwork>=0.4.6",
    "qiskit-aer>=0.13.1",
    "circuit-knitting-toolbox>=0.5.0",
    "pytket>=1.22.0",
]
requires-python = ">=3.10,<3.13"
readme = "README.md"
license = {text = "MIT"}
[project.optional-dependencies]
jupyter = [
    "jupyter>=1.0.0",
    "matplotlib>=3.7.0",
    "pylatexenc>=2.10",
]
dev = [
    "mypy>=1.0.1",
    "black>=23.1.0",
    "pytest>=7.2.1",
    "isort>=5.12.0",
]
bench = [
    "pandas>=2.0.1",
]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

