[tool.poetry]
name = "vqc"
version = "0.0.1"
description = "Quantum Virtual Machine"
authors = ["Nathaniel Tornow <nathaniel.tornow@tum.de>"]
license = "Apache Version 2.0"

[tool.poetry.dependencies]
python = "^3.9"
networkx = "^2.8.6"
sortedcontainers = "^2.4.0"
qiskit = "^0.37.2"

[tool.poetry.dev-dependencies]
mypy = "^0.971"
black = "^22.8.0"
jupyter = "^1.0.0"
matplotlib = "^3.5.3"
qiskit-aer = "^0.10.4"
pylatexenc = "^2.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
