[tool.poetry]
name = "vqc"
version = "0.0.1"
description = "Virtual Quantum Computing"
authors = ["Nathaniel Tornow <nathaniel.tornow@tum.de>"]

[tool.poetry.dependencies]
python = "^3.9.0"
qiskit-terra = "^0.22.0"
qiskit-aer = "^0.11.0"
qiskit-ibmq-provider = "^0.19.2"
networkx = "^2.8.7"

[tool.poetry.dev-dependencies]
black = "^22.10.0"
mypy = "^0.982"
isort = "^5.10.1"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
