[project]
name = "Quantum Virtual Machine"
version = "0.0.1"
description = "Framework for Virtual and Distributed Quantum Computing"
authors = [
    {name = "Nathaniel Tornow", email = "nathaniel.tornow@tum.de"},
]
dependencies = [
    "qiskit>=0.41.1",
    "networkx>=3.0",
    "setuptools>=67.6.0",
    "clingo>=5.6.2",
    "numpy>=1.23.5",
    "qiskit-aer>=0.13.1",
    "quimb>=1.7.0",
    "metis>=0.2a5",
    "pymetis>=2023.1.1",
    "kahypar>=1.3.5",
]
requires-python = ">=3.10,<3.13"
readme = "README.md"
license = {text = "MIT"}
[project.optional-dependencies]
jupyter = [
    "jupyter>=1.0.0",
    "pylatexenc>=2.10",
]
dev = [
    "mypy>=1.0.1",
    "black>=23.1.0",
    "pytest>=7.2.1",
    "isort>=5.12.0",
    "pip>=23.3.2",
]
bench = [
    "pandas>=2.0.1",
    "mqt-bench>=1.0.7",
    "matplotlib>=3.8.2",
]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

