[tool.poetry]
name = "qvm"
version = "0.0.1"
description = "Quantum Virtual Machine"
authors = ["Nathaniel Tornow <nathaniel.tornow@tum.de>"]
license = "Apache Version 2.0"

[tool.poetry.dependencies]
python = "^3.9.0"
qiskit = "^0.37.1"
networkx = "^2.8.5"
lithops = "^2.7.0"
sortedcontainers = "^2.4.0"

[tool.poetry.dev-dependencies]
mypy = "^0.971"
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
