[tool.poetry]
name = "qvm"
version = "0.1.0"
description = ""
authors = ["Nathaniel Tornow <nathaniel.tornow@tum.de>"]

[tool.poetry.dependencies]
python = "3.9.6"
numpy = "^1.23.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
